### ISSUE TITLE
Novas coisas

### ISSUE THREAD

**Issue by FernandaBernardo** [FernandaBernardo/space-game#1]
<link href="https://fonts.googleapis.com/css?family=Audiowide" rel="stylesheet">
font-family: 'Audiowide', cursive;

<button type="reset">

**Comment by luiz** [comment]
tabindex: -1

**Comment by luiz** [comment]
input type reset

**Comment by luiz** [comment]
100vh e 100vw

**Comment by JulianoDotto** [comment]
#pause-button + label{
...
z-index: 11
}
.pause-container {
    ...
    height: 100%;
   ...
    /*top: calc(32px + 0.3em); */
}

/*.pause-container:before {...} */

**Comment by FernandaBernardo** [comment]
é bem justo colocar z-index no pause hahaha
